### PR TITLE
Lua 5.1 file handles

### LINKED ISSUE #27: luaL_Stream

### PR DESCRIPTION
**Pull request by daurnimator**
Closes #27

Need to create wiki page after merge

### CODE REVIEW

**Comment by siffiejoe** [comment]
We once had `luaL_Stream` in Compat-5.2 and we (I) removed it due to problems with Lua 5.1 in general and LuaJIT in particular. See keplerproject/lua-compat-5.2#10. I'll take a closer look again, but I'm not sure what may have changed in the meantime.

**Comment by daurnimator** [comment]
Compared to that compat-5.2 issue I'm not bothering with the `closef` member: if someone tries to use `closef` with this PR they'll get a compile-time error.
Here I just want to be able to support the lua 5.2+ idiom: `luaL_Stream *fh = luaL_checkudata(L, idx, LUA_FILEHANDLE);`

**Comment by daurnimator** [comment]
@siffiejoe any thoughts?

**Comment by daurnimator** [comment]
Wrote wiki entry: https://github.com/keplerproject/lua-compat-5.3/wiki/luaL_Stream

**Comment by siffiejoe** [comment]
Thanks.

**Pull request merged**
